name: release

on: 
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and publish 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish to npmjs Package Registry
        run: npm publish --registry=https://registry.npmjs.org/ --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Set up Node.js environment for GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: Publish to GitHub npm Package Registry
        run: npm publish --registry=https://npm.pkg.github.com --access public
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: base64Gen
          path: ./dist